import { useState } from 'react';
import { apiBase } from '../lib/api';
type Tab = 'performance' | 'risk' | 'hotkeys' | 'data' | 'audit';
const tabs: Array<[Tab, string]> = [['performance', 'Geral & Performance do PC'], ['risk', 'Gerenciamento de Risco Avançado'], ['hotkeys', 'Atalhos do Teclado'], ['data', 'Dados & Gráficos'], ['audit', 'Auditoria & Diagnóstico']];
export default function AdvancedSettingsPanel() {
  const [tab, setTab] = useState<Tab>('performance'); const [risk, setRisk] = useState(() => { try { return JSON.parse(localStorage.getItem('xau-ai-pro-risk-limits') || '{"maxVolume":"0.10","dailyLoss":"2","maxExposure":"5","maxPositions":"5"}') as { maxVolume: string; dailyLoss: string; maxExposure: string; maxPositions: string }; } catch { return { maxVolume: '0.10', dailyLoss: '2', maxExposure: '5', maxPositions: '5' }; } });
  const updateRisk = (key: keyof typeof risk, value: string) => { const next = { ...risk, [key]: value }; setRisk(next); localStorage.setItem('xau-ai-pro-risk-limits', JSON.stringify(next)); };
  return <div className="card advanced-settings"><div className="settings-tabs" role="tablist" aria-label="Configuração avançada">{tabs.map(([id, label]) => <button key={id} type="button" role="tab" aria-selected={tab === id} className={`btn sm ${tab === id ? 'primary' : 'ghost'}`} onClick={() => setTab(id)}>{label}</button>)}</div>
    {tab === 'performance' && <div><h2>Geral & Performance do PC</h2><div className="grid cols-3"><div className="field"><label htmlFor="perf-refresh">Intervalo de atualização (ms)</label><input id="perf-refresh" type="number" min="1000" defaultValue="5000" /></div><div className="field"><label htmlFor="perf-list">Limite de linhas em tabelas</label><input id="perf-list" type="number" min="50" defaultValue="500" /></div><div className="field"><label htmlFor="perf-mode">Modo de desempenho</label><select id="perf-mode" defaultValue="balanced"><option value="balanced">Balanceado</option><option value="low">Economia de recursos</option><option value="high">Alta atualização</option></select></div></div><p className="hint">Atualizações em lote e listas grandes devem preservar responsividade no desktop e no Android.</p></div>}
    {tab === 'risk' && <div><h2>Gerenciamento de Risco Avançado</h2><div className="grid cols-4">{([['maxVolume', 'Volume máximo'], ['dailyLoss', 'Perda diária máxima (%)'], ['maxExposure', 'Exposição máxima (%)'], ['maxPositions', 'Máximo de posições']] as const).map(([key, label]) => <div className="field" key={key}><label htmlFor={`risk-${key}`}>{label}</label><input id={`risk-${key}`} type="number" min="0" step="any" value={risk[key]} onChange={e => updateRisk(key, e.target.value)} /></div>)}</div><div className="switch-row"><span>Kill switch armado por padrão</span><span className="chip ok">Ativo</span></div><p className="hint">Limites salvos localmente e revalidados pela corretora antes de cada comando.</p></div>}
    {tab === 'hotkeys' && <div><h2>Atalhos do Teclado</h2><div className="tbl-wrap"><table className="tbl"><thead><tr><th>Ação</th><th>Atalho</th><th>Proteção</th></tr></thead><tbody>{[['Atualizar dados', 'Ctrl + R', 'Nenhuma'], ['Abrir Configuração', 'Ctrl + ,', 'Nenhuma'], ['Selecionar compra', 'B', 'Confirmação'], ['Selecionar venda', 'S', 'Confirmação'], ['Fechar posição', 'C', 'Confirmação'], ['Parada de emergência', 'Ctrl + Shift + X', 'Dupla confirmação']].map(([action, key, guard]) => <tr key={action}><td>{action}</td><td><kbd>{key}</kbd></td><td>{guard}</td></tr>)}</tbody></table></div><p className="hint">Atalhos de negociação nunca ignoram limites, permissões ou confirmação.</p></div>}
    {tab === 'data' && <div><h2>Dados & Gráficos</h2><div className="grid cols-3"><div className="switch-row"><span>Dados da corretora ativa</span><span className="chip ok">Prioridade 1</span></div><div className="switch-row"><span>Fontes públicas de mercado</span><span className="chip ok">Permitidas</span></div><div className="switch-row"><span>Dados simulados</span><span className="chip danger">Bloqueados</span></div></div><div className="hint">Fontes externas mostram contexto e não executam operações: Binance/MEXC, CoinGecko, FRED e calendário econômico.</div></div>}
    {tab === 'audit' && <div><h2>Auditoria & Diagnóstico</h2><div className="grid cols-4"><div><span className="kpi-label">Comandos</span><strong>Registrados</strong></div><div><span className="kpi-label">Sessões</span><strong>Monitoradas</strong></div><div><span className="kpi-label">Saques</span><strong className="neg">Bloqueados</strong></div><div><span className="kpi-label">Dados</span><strong>Origem exibida</strong></div></div><button className="btn sm ghost" type="button" onClick={() => window.open(`${apiBase()}/api/health`, '_blank', 'noopener,noreferrer')}>Abrir diagnóstico do gateway</button><p className="hint">Erros de conexão, latência, reconexões e comandos ficam disponíveis para auditoria.</p></div>}
  </div>;
}
