import { useState } from 'react';
import { apiBase } from '../lib/api';
import type { BrokerId, MarketType } from '../lib/brokers';

const BROKERS: Array<{ id: BrokerId; label: string }> = [{ id: 'mt5', label: 'MetaTrader 5' }, { id: 'mexc', label: 'MEXC' }, { id: 'binance', label: 'Binance' }];
export default function BrokerOnboardingPanel() {
  const [broker, setBroker] = useState<BrokerId>('mt5'); const [market, setMarket] = useState<MarketType>('crypto-spot'); const [name, setName] = useState(''); const [status, setStatus] = useState('Nenhuma sessão validada');
  const connect = async () => { if (!name.trim()) { setStatus('Informe um nome para identificar a conta.'); return; } if (broker === 'binance') { setStatus('Binance está preparada, mas a API permanece pausada.'); return; } setStatus('Validando conta e permissões…'); try { const response = await fetch(`${apiBase()}/api/universal/account?broker=${broker}&market=${market}`, { signal: AbortSignal.timeout(10000) }); const data = await response.json() as { ok?: boolean; error?: string; withdrawals_enabled?: boolean }; if (!response.ok || !data.ok) throw new Error(data.error || `HTTP ${response.status}`); setStatus(`Sessão ${name.trim()} validada · ${broker.toUpperCase()} · ${market} · leitura disponível · saque bloqueado.`); } catch (error) { setStatus(`Não foi possível validar: ${error instanceof Error ? error.message : 'gateway indisponível'}`); } };
  return <details className="drawer" open><summary>Primeiro acesso · conectar corretora</summary><div className="drawer-body"><p className="muted">Adicione uma conta. A validação começa somente em leitura.</p><div className="grid cols-3"><div className="field"><label htmlFor="onboard-broker">Corretora</label><select id="onboard-broker" value={broker} onChange={(e) => setBroker(e.target.value as BrokerId)}>{BROKERS.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div><div className="field"><label htmlFor="onboard-market">Mercado</label><select id="onboard-market" value={market} onChange={(e) => setMarket(e.target.value as MarketType)}><option value="crypto-spot">Cripto Spot</option><option value="crypto-futures">Cripto Futures</option><option value="metals">Metais</option><option value="forex">Forex</option></select></div><div className="field"><label htmlFor="onboard-name">Nome da sessão</label><input id="onboard-name" name="account-name" autoComplete="off" placeholder="Ex.: Binance principal…" value={name} onChange={(e) => setName(e.target.value)} /></div></div><div className="btn-row"><button className="btn primary" type="button" onClick={connect}>Validar conexão</button><span className="chip warn">REAL exige ativação</span></div><div className="hint" role="status" aria-live="polite">{status}</div></div></details>;
}
