import { useState } from 'react';
import { apiBase } from '../lib/api';
import { assetIcon } from '../lib/assetIcons';

const GATEWAY = `${apiBase()}`;
type Quote = { symbol: string; bid: number; ask: number; spread: number; digits: number; source?: string };
export default function RobotCommandPanel({ symbol, quotes = [] }: { symbol: string; quotes?: Quote[]; onSelectSymbol?: (symbol: string) => void }) {
  const [side, setSide] = useState<'BUY' | 'SELL'>('BUY'); const [volume, setVolume] = useState('0.01'); const [sl, setSl] = useState(''); const [tp, setTp] = useState(''); const [busy, setBusy] = useState(false); const [msg, setMsg] = useState('Selecione uma sessão e um ativo para começar.');
  const call = async (path: string, data: Record<string, unknown> = {}) => { setBusy(true); try { const r = await fetch(GATEWAY + path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...data, confirm_demo: true }) }); const d = await r.json(); setMsg(r.ok && d.ok ? `Comando confirmado · ${path.split('/').pop()}` : `Recusado: ${d.error ?? d.comment ?? `HTTP ${r.status}`}`); } catch (e) { setMsg(`Gateway indisponível: ${e instanceof Error ? e.message : 'erro'}`); } finally { setBusy(false); } };
  const disabled = busy || !symbol;
  return <div className="card robot-command-panel" style={{ marginTop: 14 }}><div className="btn-row" style={{ justifyContent: 'space-between', marginTop: 0 }}><div><h2 style={{ margin: 0 }}><span aria-hidden="true">{assetIcon(symbol || 'ASSET')}</span> Mesa Operacional · {symbol || 'ativo não selecionado'}</h2><span className="muted">MT5 · MEXC · Binance · Spot · Futures · Forex · Índices · Metais</span></div><span className="chip warn">Sessão segura</span></div><div className="grid cols-4" style={{ marginTop: 12 }}><div className="field"><label htmlFor="op-side">Lado</label><select id="op-side" value={side} onChange={e => setSide(e.target.value as 'BUY' | 'SELL')}><option>BUY</option><option>SELL</option></select></div><div className="field"><label htmlFor="op-volume">Quantidade / lote</label><input id="op-volume" type="number" min="0" step="any" value={volume} onChange={e => setVolume(e.target.value)} /></div><div className="field"><label htmlFor="op-sl">Stop Loss</label><input id="op-sl" type="number" step="any" value={sl} onChange={e => setSl(e.target.value)} /></div><div className="field"><label htmlFor="op-tp">Take Profit</label><input id="op-tp" type="number" step="any" value={tp} onChange={e => setTp(e.target.value)} /></div></div><div className="btn-row"><button className="btn primary" type="button" onClick={() => void call('/api/demo/order', { symbol, side, volume: Number(volume), sl: Number(sl), tp: Number(tp) })} disabled={disabled}>Executar {side}</button><button className="btn ghost" type="button" onClick={() => void call('/api/demo/close', { symbol })} disabled={disabled}>Fechar posição</button><button className="btn ghost" type="button" onClick={() => void call('/api/demo/set-protection', { symbol, sl: Number(sl), tp: Number(tp) })} disabled={disabled}>Aplicar proteção</button><button className="btn ghost" type="button" onClick={() => void call('/api/demo/breakeven', { symbol })} disabled={disabled}>Break-even</button><button className="btn ghost" type="button" onClick={() => void call('/api/demo/trailing', { symbol, distance: 10 })} disabled={disabled}>Trailing</button><button className="btn danger" type="button" onClick={() => void call('/api/demo/close-all')} disabled={busy}>Fechar tudo</button></div><div className="hint" role="status" aria-live="polite">{msg}</div>{quotes.length > 0 && <div className="hint">Mercado: {quotes.length} ativos recebidos · dados reais da sessão ativa.</div>}</div>;
}
