import { useState } from 'react';
import { apiBase } from '../lib/api';

const MT5 = `${apiBase()}`;

export default function StrategyOperationsPanel({ symbol, connected }: { symbol: string; connected: boolean }) {
  const [status, setStatus] = useState('Aguardando verificação'); const [busy, setBusy] = useState(false);
  const validate = async () => { setBusy(true); try { const response = await fetch(`${MT5}/api/status`, { signal: AbortSignal.timeout(5000) }); const data = await response.json() as { terminal_connected?: boolean; account?: { trade_allowed?: boolean } }; setStatus(response.ok && data.terminal_connected ? `MT5 sincronizado · AutoTrading ${data.account?.trade_allowed ? 'ativo' : 'desativado'}` : 'MT5 indisponível'); } catch { setStatus('Gateway indisponível'); } finally { setBusy(false); } };
  const openHistory = () => { window.dispatchEvent(new CustomEvent('xau-ai-pro:navigate', { detail: 'history' })); setStatus(`Histórico solicitado para ${symbol}`); };
  return <div className="card" style={{ marginTop: 14 }}><div className="btn-row" style={{ justifyContent: 'space-between', marginTop: 0 }}><h2 style={{ margin: 0 }}>Estratégia Quantum · controle</h2><span className={`chip ${connected ? 'ok' : 'warn'}`}>{connected ? 'EA conectado' : 'EA desconectado'}</span></div><div className="grid cols-4" style={{ marginTop: 12 }}><div className="card"><span className="kpi-label">Ativo</span><strong>{symbol}</strong><span className="kpi-sub">seleção atual do Robô</span></div><div className="card"><span className="kpi-label">Modelo</span><strong>Governado</strong><span className="kpi-sub">troca automática bloqueada</span></div><div className="card"><span className="kpi-label">Dataset</span><strong>MT5 histórico</strong><span className="kpi-sub">validar janela/out-of-sample</span></div><div className="card"><span className="kpi-label">Execução</span><strong>Manual DEMO</strong><span className="kpi-sub">ordem real bloqueada</span></div></div><div className="btn-row" style={{ marginTop: 12 }}><button className="btn sm primary" type="button" onClick={() => void validate()} disabled={busy}>{busy ? 'Validando...' : 'Validar ambiente MT5'}</button><button className="btn sm ghost" type="button" onClick={openHistory}>Abrir histórico do ativo</button><span className="chip">{status}</span></div><div className="hint" style={{ marginTop: 10 }}>A estratégia só pode ser promovida após dataset identificado, separação temporal, métricas fora da amostra e confirmação manual. Este painel não substitui o Strategy Tester do MT5.</div></div>;
}
