import { useState } from 'react';

export default function StrategyGovernancePanel({ symbol }: { symbol: string }) {
  const [strategy, setStrategy] = useState('Pullback + TrendFilter');
  const [timeframe, setTimeframe] = useState('M5');
  const [direction, setDirection] = useState('BUY');
  return <div className="card strategy-study-panel" style={{ marginTop: 14 }}><div className="btn-row" style={{ justifyContent: 'space-between', marginTop: 0 }}><h2 style={{ margin: 0 }}>Estratégia & validação operacional</h2><span className="chip warn">Estudo DEMO</span></div><div className="grid cols-4" style={{ marginTop: 12 }}><div className="field"><label htmlFor="strategy-select">Estratégia</label><select id="strategy-select" value={strategy} onChange={e=>setStrategy(e.target.value)}><option>Pullback + TrendFilter</option><option>Rompimento de volatilidade</option><option>Reversão RSI + suporte</option><option>Momentum EMA + volume</option></select></div><div className="field"><label htmlFor="strategy-timeframe">Timeframe</label><select id="strategy-timeframe" value={timeframe} onChange={e=>setTimeframe(e.target.value)}><option>M5</option><option>M15</option><option>H1</option><option>H4</option></select></div><div className="field"><label htmlFor="strategy-direction">Direção</label><select id="strategy-direction" value={direction} onChange={e=>setDirection(e.target.value)}><option>BUY</option><option>SELL</option></select></div><div className="card"><span className="kpi-label">Ativo</span><strong>{symbol}</strong><span className="kpi-sub">Estudo separado da execução</span></div></div><div className="strategy-rule-grid"><div><strong>Entrada</strong><span>EMA 20/50, filtro de tendência e confirmação do candle.</span></div><div><strong>Indicadores</strong><span>RSI 14 · ATR 14 · volume · suporte/resistência.</span></div><div><strong>Gestão</strong><span>SL/TP obrigatório e risco controlado no Deck Quantum.</span></div><div><strong>Validação</strong><span>Histórico MT5 separado da execução e janela fora da amostra.</span></div></div><div className="hint" role="status">Modelo selecionado: <strong>{strategy}</strong> · {timeframe} · {direction}. A montagem não envia ordens.</div></div>;
}

