import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { useAppStore } from '../../hooks/useAppStore';
import UniversalConnectivityPanel from '../UniversalConnectivityPanel';

type Hardware = { os: string; architecture: string; cpu_name?: string; cpu_cores: number; cpu_usage_percent?: number; memory_total_gb?: number; memory_available_gb?: number; disk_total_gb?: number; disk_free_gb?: number; cpu_temperature_c?: number; gpu_name?: string; };
type Sensor = { Text?: string; Type?: string; Value?: string; Children?: Sensor[] };
const flatten = (node: Sensor, out: Sensor[] = []) => { if (node.Type && node.Value) out.push(node); (node.Children ?? []).forEach(child => flatten(child, out)); return out; };
const readSensor = (nodes: Sensor[], type: string, names: string[]) => { const item = nodes.find(node => node.Type === type && names.some(name => (node.Text ?? '').toLowerCase().includes(name))); const match = item?.Value?.replace(',', '.').match(/-?\d+(?:\.\d+)?/); return match ? Number(match[0]) : undefined; };
const gaugeColor = (value: number) => value > 80 ? '#ef4444' : value > 60 ? '#eab308' : 'var(--ok)';

export default function SystemMonitorTab() {
  const systemState = useAppStore(state => state.systemState); const wsConnected = useAppStore(state => state.wsConnected); const [hardware, setHardware] = useState<Hardware | null>(null); const [sensors, setSensors] = useState<Sensor[]>([]);
  useEffect(() => { let active = true; const loadHardware = async () => { try { const value = await invoke<Hardware>('hardware_telemetry'); if (active) setHardware(value); } catch {} }; const loadSensors = async () => { try { const response = await fetch('http://127.0.0.1:8085/data.json', { signal: AbortSignal.timeout(3000) }); if (response.ok && active) setSensors(flatten(await response.json() as Sensor)); } catch { if (active) setSensors([]); } }; void loadHardware(); void loadSensors(); const hardwareTimer = window.setInterval(loadHardware, 30000); const sensorTimer = window.setInterval(loadSensors, 5000); return () => { active = false; window.clearInterval(hardwareTimer); window.clearInterval(sensorTimer); }; }, []);
  const lhmTemp = readSensor(sensors, 'Temperature', ['cpu package', 'core max', 'core average']); const lhmGpuTemp = readSensor(sensors, 'Temperature', ['gpu core', 'gpu temperature']); const lhmLoad = readSensor(sensors, 'Load', ['cpu total']); const temperature = lhmTemp ?? hardware?.cpu_temperature_c; const cpu = lhmLoad ?? hardware?.cpu_usage_percent ?? 0; const total = hardware?.memory_total_gb ?? 0; const free = hardware?.memory_available_gb ?? 0; const memory = total ? ((total - free) / total) * 100 : 0; const tempReady = typeof temperature === 'number' && temperature > 0; const sensorSource = lhmTemp != null ? 'LibreHardwareMonitor' : hardware?.cpu_temperature_c != null ? 'Tauri/WMI' : 'nenhum sensor';
  return <div><div className="page-head"><div><h1>Monitor do Sistema</h1><span className="muted">Leituras locais reais, atualização suave a cada 30 segundos</span></div><span className={`chip ${wsConnected ? 'ok' : 'danger'}`}>{wsConnected ? 'Online' : 'Offline'}</span></div>
    <div className="grid cols-4" style={{ marginBottom: 14 }}><div className="card"><span className="kpi-label">CPU · carga</span><div className="kpi-value">{cpu.toFixed(0)}%</div><span className="kpi-sub">{hardware?.cpu_cores ?? '--'} threads · leitura instantânea</span></div><div className="card"><span className="kpi-label">RAM · ocupação</span><div className="kpi-value">{total ? `${memory.toFixed(0)}%` : '—'}</div><span className="kpi-sub">{total ? `${(total - free).toFixed(1)} / ${total.toFixed(1)} GB` : 'sensor indisponível'}</span></div><div className="card"><span className="kpi-label">CPU · temperatura</span><div className="kpi-value" style={{ color: tempReady ? gaugeColor(temperature as number) : undefined }}>{tempReady ? `${(temperature as number).toFixed(1)}°C` : '—'}</div><span className="kpi-sub">Fonte: {sensorSource}</span></div><div className="card"><span className="kpi-label">Core · integridade</span><div className="kpi-value" style={{ fontSize: 20 }}>{systemState?.status ?? 'aguardando'}</div><span className="kpi-sub">{systemState ? `${Math.floor(systemState.uptime_sec / 60)}m de uptime` : 'sem estado recebido'}</span></div></div>
    <div className="grid cols-2"><div className="card"><h2>Hardware e sensores</h2><div className="tbl-wrap"><table className="tbl"><tbody><tr><td>CPU</td><td>{hardware?.cpu_name ?? 'aguardando identificação'}</td></tr><tr><td>Sistema</td><td>{hardware ? `${hardware.os} · ${hardware.architecture}` : 'aguardando identificação'}</td></tr><tr><td>GPU</td><td>{hardware?.gpu_name ?? 'não detectada / opcional'}</td></tr><tr><td>Temperatura GPU</td><td>{lhmGpuTemp != null ? `${lhmGpuTemp.toFixed(1)}°C · LibreHardwareMonitor` : 'sensor GPU indisponível'}</td></tr><tr><td>MT5</td><td><span className={`chip ${systemState?.mt5_connected ? 'ok' : 'warn'}`}>{systemState?.mt5_connected ? 'Conectado' : 'Desconectado'}</span></td></tr></tbody></table></div></div><div className="card"><h2>Diagnóstico térmico</h2><p className="muted">{tempReady ? `CPU em ${temperature?.toFixed(1)}°C; fonte confirmada: ${sensorSource}.` : 'Nenhum sensor térmico respondeu. Inicie o LibreHardwareMonitor ou permita a leitura Tauri.'}</p><div className="hint">Os valores são somente leitura. Sem valores simulados, sem comandos ao MT5. Atualização a cada 30 segundos para reduzir carga e aquecimento.</div></div></div></div>;
}
